# Problema 2

In [5]:
import numpy as np 
#Crearemos un arreglo donde el primer valor sera Z con relacion que quede de la forma
Funcion_a_maximizar = []

#variable de paro
x = True
contador = 0
informacion_paso = "z"

while(x == True):
    if(contador != 0):
        informacion_paso = "X_" + str(contador)
        
            
    variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
    contador +=1
    if(variable_entrada.lower() == 'x'):
        x = False
    else:
         Funcion_a_maximizar.append(int(variable_entrada))
   

print("Funcion a Maximizar")
print(Funcion_a_maximizar)



Introduce el valor z de la funcion dada, presiona (X) si terminaste1
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste-2
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste1
Introduce el valor X_3 de la funcion dada, presiona (X) si terminastex
Funcion a Maximizar
[1, -2, 1]


In [9]:
#Crearemos las restricciones para este sistema
#Estara limitado hasta un máximo de 5 restricciones

#primero para 3 restricciones
def restriccion():
    restriccion = []
    #variable de paro
    x = True
    contador = 1
    informacion_paso = ""

    while(x == True):
        
        informacion_paso = "X_" + str(contador)

        print("Escribe 0 si quieres que la variable este vacia")
        variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
        contador +=1
        if(variable_entrada.lower() == 'x'):
            x = False
        else:
             restriccion.append(int(variable_entrada))

    desigualdad = input('Escribe el valor de la desigualdad')
    restriccion.append(int(desigualdad))
    
    print("Valor de la restriccion")
    print(restriccion)
    return restriccion

In [10]:
#Total de restricciones
print("Introduce la primera restriccion")
restriccion_1 = restriccion()
print("Introduce la segunda restriccion")
restriccion_2 = restriccion()
print("Introduce la tercera restriccion")
restriccion_3 = restriccion()

Introduce la primera restriccion
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste1
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste1
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_3 de la funcion dada, presiona (X) si terminaste1
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_4 de la funcion dada, presiona (X) si terminastex
Escribe el valor de la desigualdad12
Valor de la restriccion
[1, 1, 1, 12]
Introduce la segunda restriccion
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste2
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste1
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_3 de la funcion dada, presiona (X) si terminaste-1
Escribe 0 si quieres que 

In [11]:
#Usamos estos valores para la muestra
restriccion_1 = [1,1,1]
restriccion_2 = [2,1,-1]
restriccion_3 = [1,3,0]

In [12]:
if(len(restriccion_1) == len(restriccion_2) and len(restriccion_2) == len(restriccion_3)):
    print("Las longitudes de las restricciones son correctas, continuemos: ")
else:
    print("Selecciona diferentes restricciones")

Las longitudes de las restricciones son correctas, continuemos: 


In [13]:
#zNegativa  es la primera funcion , la Funcion_a_maximizar en valores negativos donde

# Z -20X_1 -10X_2

F_a_M_Transformada = []

for x in range(len(Funcion_a_maximizar)):
    valores = 0
    if(x == 0):
        valores = int(Funcion_a_maximizar[x])
    else:
        valores = int(Funcion_a_maximizar[x])*-1
    F_a_M_Transformada.append(valores)
    
print("Valor de la funcion Z transformada: ")    
print(F_a_M_Transformada)
    
min_value = min(F_a_M_Transformada)
print('Valor Minimo:', min_value, "En el indice:", F_a_M_Transformada.index(min_value))  
    

Valor de la funcion Z transformada: 
[1, 2, -1]
Valor Minimo: -1 En el indice: 2


In [14]:
#asignamos las restricciones a variables s , para despues agregar las variables pivote
s1 = (restriccion_1)
s2 = (restriccion_2)
s3 = (restriccion_3)

#seleccionamos el ultimo elemento
s1_utlimo = (s1[-1])
s2_utlimo = (s2[-1])
s3_utlimo = (s3[-1])

#quitamos por mientras el ultimo valor
s1.pop()
s2.pop()
s3.pop()

#creamos las listas pivote
pivote_1 = [1,0,0]
pivote_2 = [0,1,0]
pivote_3 = [0,0,1]
pivote_4 = [0,0,0,0]
#añadimos los valores 0 al inicio de cada lista s    
s1 = [0, *s1]
s2 = [0, *s2]
s3 = [0, *s3]
    
    
#observamos como van las listas
print(s1)
print(s2)
print(s3)

#s1 = []
#s2 = []
#s3 = []

#añadir valores pivote

s1.extend(pivote_1)
s2.extend(pivote_2)
s3.extend(pivote_3)
F_a_M_Transformada.extend(pivote_4)

#añadir ultimo valor
s1.append(s1_utlimo)
s2.append(s2_utlimo)
s3.append(s3_utlimo)

#creamos un arreglo que despues volveremos a usar
ss1 = np.array(s1)
ss2 = np.array(s2)
ss3 = np.array(s3)
print(ss1)

[0, 1, 1]
[0, 2, 1]
[0, 1, 3]
[0 1 1 1 0 0 1]


In [15]:
#metodo para agregar todas las listas dentro de una para luego transformarla en matriz
lista_general = s1.extend(s2)
lista_general = s1.extend(s3)

In [16]:
#agregamos la columna z
lista_general = s1.extend(F_a_M_Transformada)

In [17]:
lista_matriz = []
lista_matriz = s1
print(lista_matriz)

[0, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 1, 0, -1, 0, 1, 3, 0, 0, 1, 0, 1, 2, -1, 0, 0, 0, 0]


In [18]:
x = np.array(lista_matriz).reshape(4,7)
print(x)

[[ 0  1  1  1  0  0  1]
 [ 0  2  1  0  1  0 -1]
 [ 0  1  3  0  0  1  0]
 [ 1  2 -1  0  0  0  0]]


In [19]:
import pandas as pd

#Podemos visualizarlo de mejor manera con un daframe en pandas

df = pd.DataFrame(data=x )
df

0  1  2  3  4  5  6
0  0  1  1  1  0  0  1
1  0  2  1  0  1  0 -1
2  0  1  3  0  0  1  0
3  1  2 -1  0  0  0  0

In [20]:
#resultado operacion =>

fila_a_dividir = df[2]
valor_minimo_iteracion_1 = []

for x in range(len(fila_a_dividir)-1):
    print(df[6][x]/fila_a_dividir[x])
    valor_minimo_iteracion_1.append(df[6][x]/fila_a_dividir[x])
    
#eliminamos valor z 
min_value_i = min(valor_minimo_iteracion_1)    
print('Valor Minimo:', min_value_i, "En el indice:", F_a_M_Transformada.index(min_value)) 
    

1.0
-1.0
0.0
Valor Minimo: -1.0 En el indice: 2


In [21]:
#division de fila x_2 entre 8 que es el valor pivote
FE = []
for v in range(len(ss2)):
    division = ss2[v] / 2
    FE.append(division)
print(FE)

[0.0, 1.0, 0.5, 0.0, 0.5, 0.0, -0.5]


In [22]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_1
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_1
print(ss1)
CPVFS_1 = []
for u in range(len(ss1)):
    CPVFS_1.append(2)
print(CPVFS_1)    

[0 1 1 1 0 0 1]
[2, 2, 2, 2, 2, 2, 2]


In [23]:
fila_nuevaS1 = []
for f in range(len(ss1)):
    operacion = ss1[f] - (CPVFS_1[f]*FE[f])
    fila_nuevaS1.append(operacion)
print(fila_nuevaS1)    

[0.0, -1.0, 0.0, 1.0, -1.0, 0.0, 2.0]


In [24]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_3
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_3
print(ss3)
CPVFS_3 = []
for u in range(len(ss3)):
    CPVFS_3.append(2)
print(CPVFS_3)  

fila_nuevaS3 = []
for f in range(len(ss3)):
    operacion = ss3[f] - (CPVFS_3[f]*FE[f])
    fila_nuevaS3.append(operacion)
print(fila_nuevaS3) 

[0 1 3 0 0 1 0]
[2, 2, 2, 2, 2, 2, 2]
[0.0, -1.0, 2.0, 0.0, -1.0, 1.0, 1.0]


In [25]:
#Fila Vieja Z
zs = np.array(F_a_M_Transformada)
print(zs)
CPVFz = []
for u in range(len(zs)):
    CPVFz.append(-3)
print(CPVFz)  

fila_nuevaz = []
for f in range(len(zs)):
    operacion = zs[f] - (CPVFz[f]*FE[f])
    fila_nuevaz.append(operacion)
print(fila_nuevaz)    

[ 1  2 -1  0  0  0  0]
[-3, -3, -3, -3, -3, -3, -3]
[1.0, 5.0, 0.5, 0.0, 1.5, 0.0, -1.5]


In [26]:
#Aqui pueden reajustarlas con reshape
print(fila_nuevaS1)    
print(FE)
print(fila_nuevaS3) 
print(fila_nuevaz) 

[0.0, -1.0, 0.0, 1.0, -1.0, 0.0, 2.0]
[0.0, 1.0, 0.5, 0.0, 0.5, 0.0, -0.5]
[0.0, -1.0, 2.0, 0.0, -1.0, 1.0, 1.0]
[1.0, 5.0, 0.5, 0.0, 1.5, 0.0, -1.5]


In [27]:
contador = 0
for w in fila_nuevaz:
    
    if(w<0):
        print("Puede optimizarse más")
        contador = 1
    else: 
        contador = 0
if(contador == 0):
    print("Encontramos la opcion optima")

Puede optimizarse más


In [28]:
FE2 = []
for v in range(len(fila_nuevaS1)):
    division = fila_nuevaS1[v] / 2
    print(division)
    FE2.append(division)
print(FE2)

0.0
-0.5
0.0
0.5
-0.5
0.0
1.0
[0.0, -0.5, 0.0, 0.5, -0.5, 0.0, 1.0]


In [29]:
print(FE[-1:])
print(fila_nuevaz[-1:])

[-0.5]
[-1.5]


In [30]:
# PROBLEMA 3

In [36]:
import numpy as np 
#Crearemos un arreglo donde el primer valor sera Z con relacion que quede de la forma
Funcion_a_maximizar = []

#variable de paro
x = True
contador = 0
informacion_paso = "z"

while(x == True):
    if(contador != 0):
        informacion_paso = "X_" + str(contador)
        
            
    variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
    contador +=1
    if(variable_entrada.lower() == 'x'):
        x = False
    else:
         Funcion_a_maximizar.append(int(variable_entrada))
   

print("Funcion a Maximizar")
print(Funcion_a_maximizar)

Introduce el valor z de la funcion dada, presiona (X) si terminaste010
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste008
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste012
Introduce el valor X_3 de la funcion dada, presiona (X) si terminastex
Funcion a Maximizar
[10, 8, 12]


In [37]:
#Crearemos las restricciones para este sistema
#Estara limitado hasta un máximo de 5 restricciones

#primero para 3 restricciones
def restriccion():
    restriccion = []
    #variable de paro
    x = True
    contador = 1
    informacion_paso = ""

    while(x == True):
        
        informacion_paso = "X_" + str(contador)

        print("Escribe 0 si quieres que la variable este vacia")
        variable_entrada = input('Introduce el valor ' + informacion_paso +' de la funcion dada, presiona (X) si terminaste')
        contador +=1
        if(variable_entrada.lower() == 'x'):
            x = False
        else:
             restriccion.append(int(variable_entrada))

    desigualdad = input('Escribe el valor de la desigualdad')
    restriccion.append(int(desigualdad))
    
    print("Valor de la restriccion")
    print(restriccion)
    return restriccion

In [38]:
#Total de restricciones
print("Introduce la primera restriccion")
restriccion_1 = restriccion()
print("Introduce la segunda restriccion")
restriccion_2 = restriccion()
print("Introduce la tercera restriccion")
restriccion_3 = restriccion()

Introduce la primera restriccion
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste25
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste15
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_3 de la funcion dada, presiona (X) si terminaste25
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_4 de la funcion dada, presiona (X) si terminastex
Escribe el valor de la desigualdad22
Valor de la restriccion
[25, 15, 25, 22]
Introduce la segunda restriccion
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_1 de la funcion dada, presiona (X) si terminaste15
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_2 de la funcion dada, presiona (X) si terminaste30
Escribe 0 si quieres que la variable este vacia
Introduce el valor X_3 de la funcion dada, presiona (X) si terminaste20
Escribe 0 si quie

In [39]:
#Usamos estos valores para la muestra
restriccion_1 = [25,15,25]
restriccion_2 = [15,30,20]
restriccion_3 = [5,12,8]

In [40]:
if(len(restriccion_1) == len(restriccion_2) and len(restriccion_2) == len(restriccion_3)):
    print("Las longitudes de las restricciones son correctas, continuemos: ")
else:
    print("Selecciona diferentes restricciones")

Las longitudes de las restricciones son correctas, continuemos: 


In [41]:
#zNegativa  es la primera funcion , la Funcion_a_maximizar en valores negativos donde

# Z -20X_1 -10X_2

F_a_M_Transformada = []

for x in range(len(Funcion_a_maximizar)):
    valores = 0
    if(x == 0):
        valores = int(Funcion_a_maximizar[x])
    else:
        valores = int(Funcion_a_maximizar[x])*-1
    F_a_M_Transformada.append(valores)
    
print("Valor de la funcion Z transformada: ")    
print(F_a_M_Transformada)
    
min_value = min(F_a_M_Transformada)
print('Valor Minimo:', min_value, "En el indice:", F_a_M_Transformada.index(min_value))  
    

Valor de la funcion Z transformada: 
[10, -8, -12]
Valor Minimo: -12 En el indice: 2


In [42]:
#asignamos las restricciones a variables s , para despues agregar las variables pivote
s1 = (restriccion_1)
s2 = (restriccion_2)
s3 = (restriccion_3)

#seleccionamos el ultimo elemento
s1_utlimo = (s1[-1])
s2_utlimo = (s2[-1])
s3_utlimo = (s3[-1])

#quitamos por mientras el ultimo valor
s1.pop()
s2.pop()
s3.pop()

#creamos las listas pivote
pivote_1 = [1,0,0]
pivote_2 = [0,1,0]
pivote_3 = [0,0,1]
pivote_4 = [0,0,0,0]
#añadimos los valores 0 al inicio de cada lista s    
s1 = [0, *s1]
s2 = [0, *s2]
s3 = [0, *s3]
    
    
#observamos como van las listas
print(s1)
print(s2)
print(s3)

#s1 = []
#s2 = []
#s3 = []

#añadir valores pivote

s1.extend(pivote_1)
s2.extend(pivote_2)
s3.extend(pivote_3)
F_a_M_Transformada.extend(pivote_4)

#añadir ultimo valor
s1.append(s1_utlimo)
s2.append(s2_utlimo)
s3.append(s3_utlimo)

#creamos un arreglo que despues volveremos a usar
ss1 = np.array(s1)
ss2 = np.array(s2)
ss3 = np.array(s3)
print(ss1)

[0, 25, 15]
[0, 15, 30]
[0, 5, 12]
[ 0 25 15  1  0  0 25]


In [43]:
#metodo para agregar todas las listas dentro de una para luego transformarla en matriz
lista_general = s1.extend(s2)
lista_general = s1.extend(s3)

In [44]:
#agregamos la columna z
lista_general = s1.extend(F_a_M_Transformada)

In [45]:
lista_matriz = []
lista_matriz = s1
print(lista_matriz)

[0, 25, 15, 1, 0, 0, 25, 0, 15, 30, 0, 1, 0, 20, 0, 5, 12, 0, 0, 1, 8, 10, -8, -12, 0, 0, 0, 0]


In [46]:
x = np.array(lista_matriz).reshape(4,7)
print(x)

[[  0  25  15   1   0   0  25]
 [  0  15  30   0   1   0  20]
 [  0   5  12   0   0   1   8]
 [ 10  -8 -12   0   0   0   0]]


In [47]:
import pandas as pd

#Podemos visualizarlo de mejor manera con un daframe en pandas

df = pd.DataFrame(data=x )
df

0   1   2  3  4  5   6
0   0  25  15  1  0  0  25
1   0  15  30  0  1  0  20
2   0   5  12  0  0  1   8
3  10  -8 -12  0  0  0   0

In [48]:
#resultado operacion =>

fila_a_dividir = df[2]
valor_minimo_iteracion_1 = []

for x in range(len(fila_a_dividir)-1):
    print(df[6][x]/fila_a_dividir[x])
    valor_minimo_iteracion_1.append(df[6][x]/fila_a_dividir[x])
    
#eliminamos valor z 
min_value_i = min(valor_minimo_iteracion_1)    
print('Valor Minimo:', min_value_i, "En el indice:", F_a_M_Transformada.index(min_value)) 
    

1.6666666666666667
0.6666666666666666
0.6666666666666666
Valor Minimo: 0.6666666666666666 En el indice: 2


In [49]:
#division de fila x_2 entre 8 que es el valor pivote
FE = []
for v in range(len(ss2)):
    division = ss2[v] / 2
    FE.append(division)
print(FE)

[0.0, 7.5, 15.0, 0.0, 0.5, 0.0, 10.0]


In [50]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_1
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_1
print(ss1)
CPVFS_1 = []
for u in range(len(ss1)):
    CPVFS_1.append(2)
print(CPVFS_1)   

[ 0 25 15  1  0  0 25]
[2, 2, 2, 2, 2, 2, 2]


In [51]:
fila_nuevaS1 = []
for f in range(len(ss1)):
    operacion = ss1[f] - (CPVFS_1[f]*FE[f])
    fila_nuevaS1.append(operacion)
print(fila_nuevaS1)    

[0.0, 10.0, -15.0, 1.0, -1.0, 0.0, 5.0]


In [52]:
#sabemos que el indice dos es donde vamos a seleccionar el valor pivote, dentro de la fila S_3
# el valor de X_2 es = 2 entonces vamos a crear un arreglo con ese valor para ejecutar la operacion

#Fila Vieja S_3
print(ss3)
CPVFS_3 = []
for u in range(len(ss3)):
    CPVFS_3.append(2)
print(CPVFS_3)  

fila_nuevaS3 = []
for f in range(len(ss3)):
    operacion = ss3[f] - (CPVFS_3[f]*FE[f])
    fila_nuevaS3.append(operacion)
print(fila_nuevaS3) 

[ 0  5 12  0  0  1  8]
[2, 2, 2, 2, 2, 2, 2]
[0.0, -10.0, -18.0, 0.0, -1.0, 1.0, -12.0]


In [53]:
#Fila Vieja Z
zs = np.array(F_a_M_Transformada)
print(zs)
CPVFz = []
for u in range(len(zs)):
    CPVFz.append(-3)
print(CPVFz)  

fila_nuevaz = []
for f in range(len(zs)):
    operacion = zs[f] - (CPVFz[f]*FE[f])
    fila_nuevaz.append(operacion)
print(fila_nuevaz)    

[ 10  -8 -12   0   0   0   0]
[-3, -3, -3, -3, -3, -3, -3]
[10.0, 14.5, 33.0, 0.0, 1.5, 0.0, 30.0]


In [54]:
#Aqui pueden reajustarlas con reshape
print(fila_nuevaS1)    
print(FE)
print(fila_nuevaS3) 
print(fila_nuevaz) 

[0.0, 10.0, -15.0, 1.0, -1.0, 0.0, 5.0]
[0.0, 7.5, 15.0, 0.0, 0.5, 0.0, 10.0]
[0.0, -10.0, -18.0, 0.0, -1.0, 1.0, -12.0]
[10.0, 14.5, 33.0, 0.0, 1.5, 0.0, 30.0]


In [55]:
contador = 0
for w in fila_nuevaz:
    
    if(w<0):
        print("Puede optimizarse más")
        contador = 1
    else: 
        contador = 0
if(contador == 0):
    print("Encontramos la opcion optima")

Encontramos la opcion optima


In [56]:
FE2 = []
for v in range(len(fila_nuevaS1)):
    division = fila_nuevaS1[v] / 2
    print(division)
    FE2.append(division)
print(FE2)

0.0
5.0
-7.5
0.5
-0.5
0.0
2.5
[0.0, 5.0, -7.5, 0.5, -0.5, 0.0, 2.5]


In [57]:
print(FE[-1:])
print(fila_nuevaz[-1:])

[10.0]
[30.0]
