In [1]:
import numpy as np

In [2]:
D_1 = np.eye((2))

In [3]:
D_1

array([[1., 0.],
       [0., 1.]])

In [4]:
x_1 = np.array([0, 3])

In [5]:
y_1 = x_1

In [6]:
k = j = 1

In [7]:
def grad_f(y_j):
    x_1_var = y_j[0]
    x_2_var = y_j[1]
    return np.array([(4*(x_1_var - 2)**3) + 2*(x_1_var - 2*x_2_var), -4*(x_1_var - 2*x_2_var)])

In [10]:
d_1 = -1 * D_1 @ grad_f(y_1)

In [11]:
d_1

array([ 44., -24.])

In [26]:
y_j = y_1
d_j = d_1

In [37]:
y_j

array([0, 3])

In [38]:
d_j

array([ 44., -24.])

In [27]:
fun = lambda l: (y_j[0] + d_j[0]*l - 2)**4 + (y_j[0] + d_j[0]*l - 2*(y_j[1] + d_j[1]*l))**2

In [60]:
initial_guess = np.array([0.1])

In [61]:
import scipy.optimize as optimize

In [62]:
result = optimize.minimize(fun, initial_guess)

In [63]:
result

      fun: 0.3653851152616475
 hess_inv: array([[3.50153428e-05]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 22
      nit: 8
     njev: 11
   status: 0
  success: True
        x: array([0.06153484])

In [64]:
if result.success:
    fitted_params = result.x
    print(fitted_params)
else:
    raise ValueError(result.message)

[0.06153484]


In [ ]:
y_2 = y_1